name: Renovate
on:
  workflow_dispatch:

  schedule:
    - cron: '0 21 * * 0' # Every Sunday at 9PM UTC

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v32.221.1
        with:
          configurationFile: renovate-config.js
          token: ${{ secrets.renovate_token }}